// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServiceCatalog.Web.Data;

#nullable disable

namespace ServiceCatalog.Web.Migrations
{
    [DbContext(typeof(ServiceCatalogDbContext))]
    partial class ServiceCatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ServiceCatalog.Web.Models.Capability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Capabilities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ColorHex = "#EC5A62",
                            Description = "Customer Service Operations",
                            Name = "Customer Service",
                            Order = 1
                        },
                        new
                        {
                            Id = 2,
                            ColorHex = "#89878B",
                            Description = "Clinical Services Operations",
                            Name = "Clinical Services",
                            Order = 2
                        },
                        new
                        {
                            Id = 3,
                            ColorHex = "#3B3D40",
                            Description = "Human Resource Services",
                            Name = "Human Resource Services",
                            Order = 3
                        },
                        new
                        {
                            Id = 4,
                            ColorHex = "#FFB900",
                            Description = "Supply Chain Management",
                            Name = "Supply Chain",
                            Order = 4
                        },
                        new
                        {
                            Id = 5,
                            ColorHex = "#42B3D5",
                            Description = "Information Technology Services",
                            Name = "Information Technology",
                            Order = 5
                        },
                        new
                        {
                            Id = 6,
                            ColorHex = "#69D2B7",
                            Description = "Finance and Accounting Services",
                            Name = "Finance Services",
                            Order = 6
                        },
                        new
                        {
                            Id = 7,
                            ColorHex = "#B390D4",
                            Description = "Enablement and Governance",
                            Name = "Enablement & Governance",
                            Order = 7
                        },
                        new
                        {
                            Id = 8,
                            ColorHex = "#7BB1E8",
                            Description = "Procurement Services",
                            Name = "Procurement Services",
                            Order = 8
                        });
                });

            modelBuilder.Entity("ServiceCatalog.Web.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeCount")
                        .HasColumnType("int");

                    b.Property<string>("FlagUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("ServiceCatalog.Web.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CapabilityId")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CapabilityId");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("ServiceCatalog.Web.Models.ServiceApplicability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Division")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsApplicable")
                        .HasColumnType("bit");

                    b.Property<int>("ServiceProcessId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ServiceProcessId");

                    b.HasIndex("ServiceProcessId", "Division")
                        .IsUnique();

                    b.ToTable("ServiceApplicabilities");
                });

            modelBuilder.Entity("ServiceCatalog.Web.Models.ServiceProcess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.ToTable("ServiceProcesses");
                });

            modelBuilder.Entity("ServiceCatalog.Web.Models.Service", b =>
                {
                    b.HasOne("ServiceCatalog.Web.Models.Capability", "Capability")
                        .WithMany("Services")
                        .HasForeignKey("CapabilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Capability");
                });

            modelBuilder.Entity("ServiceCatalog.Web.Models.ServiceApplicability", b =>
                {
                    b.HasOne("ServiceCatalog.Web.Models.ServiceProcess", "ServiceProcess")
                        .WithMany("Applicabilities")
                        .HasForeignKey("ServiceProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceProcess");
                });

            modelBuilder.Entity("ServiceCatalog.Web.Models.ServiceProcess", b =>
                {
                    b.HasOne("ServiceCatalog.Web.Models.Service", "Service")
                        .WithMany("Processes")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("ServiceCatalog.Web.Models.Capability", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("ServiceCatalog.Web.Models.Service", b =>
                {
                    b.Navigation("Processes");
                });

            modelBuilder.Entity("ServiceCatalog.Web.Models.ServiceProcess", b =>
                {
                    b.Navigation("Applicabilities");
                });
#pragma warning restore 612, 618
        }
    }
}
